//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAGO_Pruebas.ClienteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/TAGO_Servicios.Dominio")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TAGO_Pruebas.ClienteService.Tarjeta[] TarjetasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TAGO_Pruebas.ClienteService.Tarjeta[] Tarjetas {
            get {
                return this.TarjetasField;
            }
            set {
                if ((object.ReferenceEquals(this.TarjetasField, value) != true)) {
                    this.TarjetasField = value;
                    this.RaisePropertyChanged("Tarjetas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tarjeta", Namespace="http://schemas.datacontract.org/2004/07/TAGO_Servicios.Dominio")]
    [System.SerializableAttribute()]
    public partial class Tarjeta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CVVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVV {
            get {
                return this.CVVField;
            }
            set {
                if ((object.ReferenceEquals(this.CVVField, value) != true)) {
                    this.CVVField = value;
                    this.RaisePropertyChanged("CVV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((this.ClienteField.Equals(value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaVencimientoField, value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteService.IClienteService")]
    public interface IClienteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/RegistrarCliente", ReplyAction="http://tempuri.org/IClienteService/RegistrarClienteResponse")]
        TAGO_Pruebas.ClienteService.Cliente RegistrarCliente(TAGO_Pruebas.ClienteService.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/RegistrarCliente", ReplyAction="http://tempuri.org/IClienteService/RegistrarClienteResponse")]
        System.Threading.Tasks.Task<TAGO_Pruebas.ClienteService.Cliente> RegistrarClienteAsync(TAGO_Pruebas.ClienteService.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ModificarCliente", ReplyAction="http://tempuri.org/IClienteService/ModificarClienteResponse")]
        TAGO_Pruebas.ClienteService.Cliente ModificarCliente(TAGO_Pruebas.ClienteService.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ModificarCliente", ReplyAction="http://tempuri.org/IClienteService/ModificarClienteResponse")]
        System.Threading.Tasks.Task<TAGO_Pruebas.ClienteService.Cliente> ModificarClienteAsync(TAGO_Pruebas.ClienteService.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ConsultarCliente", ReplyAction="http://tempuri.org/IClienteService/ConsultarClienteResponse")]
        TAGO_Pruebas.ClienteService.Cliente ConsultarCliente(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ConsultarCliente", ReplyAction="http://tempuri.org/IClienteService/ConsultarClienteResponse")]
        System.Threading.Tasks.Task<TAGO_Pruebas.ClienteService.Cliente> ConsultarClienteAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/RegistrarTarjeta", ReplyAction="http://tempuri.org/IClienteService/RegistrarTarjetaResponse")]
        TAGO_Pruebas.ClienteService.Tarjeta RegistrarTarjeta(TAGO_Pruebas.ClienteService.Tarjeta tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/RegistrarTarjeta", ReplyAction="http://tempuri.org/IClienteService/RegistrarTarjetaResponse")]
        System.Threading.Tasks.Task<TAGO_Pruebas.ClienteService.Tarjeta> RegistrarTarjetaAsync(TAGO_Pruebas.ClienteService.Tarjeta tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ModificarTarjeta", ReplyAction="http://tempuri.org/IClienteService/ModificarTarjetaResponse")]
        TAGO_Pruebas.ClienteService.Tarjeta ModificarTarjeta(TAGO_Pruebas.ClienteService.Tarjeta tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ModificarTarjeta", ReplyAction="http://tempuri.org/IClienteService/ModificarTarjetaResponse")]
        System.Threading.Tasks.Task<TAGO_Pruebas.ClienteService.Tarjeta> ModificarTarjetaAsync(TAGO_Pruebas.ClienteService.Tarjeta tarjeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/EliminarTarjeta", ReplyAction="http://tempuri.org/IClienteService/EliminarTarjetaResponse")]
        int EliminarTarjeta(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/EliminarTarjeta", ReplyAction="http://tempuri.org/IClienteService/EliminarTarjetaResponse")]
        System.Threading.Tasks.Task<int> EliminarTarjetaAsync(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteServiceChannel : TAGO_Pruebas.ClienteService.IClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<TAGO_Pruebas.ClienteService.IClienteService>, TAGO_Pruebas.ClienteService.IClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TAGO_Pruebas.ClienteService.Cliente RegistrarCliente(TAGO_Pruebas.ClienteService.Cliente cliente) {
            return base.Channel.RegistrarCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<TAGO_Pruebas.ClienteService.Cliente> RegistrarClienteAsync(TAGO_Pruebas.ClienteService.Cliente cliente) {
            return base.Channel.RegistrarClienteAsync(cliente);
        }
        
        public TAGO_Pruebas.ClienteService.Cliente ModificarCliente(TAGO_Pruebas.ClienteService.Cliente cliente) {
            return base.Channel.ModificarCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<TAGO_Pruebas.ClienteService.Cliente> ModificarClienteAsync(TAGO_Pruebas.ClienteService.Cliente cliente) {
            return base.Channel.ModificarClienteAsync(cliente);
        }
        
        public TAGO_Pruebas.ClienteService.Cliente ConsultarCliente(string Email) {
            return base.Channel.ConsultarCliente(Email);
        }
        
        public System.Threading.Tasks.Task<TAGO_Pruebas.ClienteService.Cliente> ConsultarClienteAsync(string Email) {
            return base.Channel.ConsultarClienteAsync(Email);
        }
        
        public TAGO_Pruebas.ClienteService.Tarjeta RegistrarTarjeta(TAGO_Pruebas.ClienteService.Tarjeta tarjeta) {
            return base.Channel.RegistrarTarjeta(tarjeta);
        }
        
        public System.Threading.Tasks.Task<TAGO_Pruebas.ClienteService.Tarjeta> RegistrarTarjetaAsync(TAGO_Pruebas.ClienteService.Tarjeta tarjeta) {
            return base.Channel.RegistrarTarjetaAsync(tarjeta);
        }
        
        public TAGO_Pruebas.ClienteService.Tarjeta ModificarTarjeta(TAGO_Pruebas.ClienteService.Tarjeta tarjeta) {
            return base.Channel.ModificarTarjeta(tarjeta);
        }
        
        public System.Threading.Tasks.Task<TAGO_Pruebas.ClienteService.Tarjeta> ModificarTarjetaAsync(TAGO_Pruebas.ClienteService.Tarjeta tarjeta) {
            return base.Channel.ModificarTarjetaAsync(tarjeta);
        }
        
        public int EliminarTarjeta(int codigo) {
            return base.Channel.EliminarTarjeta(codigo);
        }
        
        public System.Threading.Tasks.Task<int> EliminarTarjetaAsync(int codigo) {
            return base.Channel.EliminarTarjetaAsync(codigo);
        }
    }
}
