//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAGO_Presentacion.ReservaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reserva", Namespace="http://schemas.datacontract.org/2004/07/TAGO_Servicios.Dominio")]
    [System.SerializableAttribute()]
    public partial class Reserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaRecojoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaRegistroReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destino {
            get {
                return this.DestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinoField, value) != true)) {
                    this.DestinoField = value;
                    this.RaisePropertyChanged("Destino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaRecojoCliente {
            get {
                return this.FechaRecojoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaRecojoClienteField, value) != true)) {
                    this.FechaRecojoClienteField = value;
                    this.RaisePropertyChanged("FechaRecojoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaRegistroReserva {
            get {
                return this.FechaRegistroReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaRegistroReservaField, value) != true)) {
                    this.FechaRegistroReservaField = value;
                    this.RaisePropertyChanged("FechaRegistroReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstadoReserva {
            get {
                return this.IdEstadoReservaField;
            }
            set {
                if ((this.IdEstadoReservaField.Equals(value) != true)) {
                    this.IdEstadoReservaField = value;
                    this.RaisePropertyChanged("IdEstadoReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReserva {
            get {
                return this.IdReservaField;
            }
            set {
                if ((this.IdReservaField.Equals(value) != true)) {
                    this.IdReservaField = value;
                    this.RaisePropertyChanged("IdReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Importe {
            get {
                return this.ImporteField;
            }
            set {
                if ((this.ImporteField.Equals(value) != true)) {
                    this.ImporteField = value;
                    this.RaisePropertyChanged("Importe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origen {
            get {
                return this.OrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigenField, value) != true)) {
                    this.OrigenField = value;
                    this.RaisePropertyChanged("Origen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa {
            get {
                return this.PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaField, value) != true)) {
                    this.PlacaField = value;
                    this.RaisePropertyChanged("Placa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservaService.IReservaService")]
    public interface IReservaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/RegistrarReserva", ReplyAction="http://tempuri.org/IReservaService/RegistrarReservaResponse")]
        TAGO_Presentacion.ReservaService.Reserva RegistrarReserva(TAGO_Presentacion.ReservaService.Reserva entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/RegistrarReserva", ReplyAction="http://tempuri.org/IReservaService/RegistrarReservaResponse")]
        System.Threading.Tasks.Task<TAGO_Presentacion.ReservaService.Reserva> RegistrarReservaAsync(TAGO_Presentacion.ReservaService.Reserva entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/CancelarReserva", ReplyAction="http://tempuri.org/IReservaService/CancelarReservaResponse")]
        TAGO_Presentacion.ReservaService.Reserva CancelarReserva(TAGO_Presentacion.ReservaService.Reserva entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/CancelarReserva", ReplyAction="http://tempuri.org/IReservaService/CancelarReservaResponse")]
        System.Threading.Tasks.Task<TAGO_Presentacion.ReservaService.Reserva> CancelarReservaAsync(TAGO_Presentacion.ReservaService.Reserva entidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservaServiceChannel : TAGO_Presentacion.ReservaService.IReservaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservaServiceClient : System.ServiceModel.ClientBase<TAGO_Presentacion.ReservaService.IReservaService>, TAGO_Presentacion.ReservaService.IReservaService {
        
        public ReservaServiceClient() {
        }
        
        public ReservaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TAGO_Presentacion.ReservaService.Reserva RegistrarReserva(TAGO_Presentacion.ReservaService.Reserva entidad) {
            return base.Channel.RegistrarReserva(entidad);
        }
        
        public System.Threading.Tasks.Task<TAGO_Presentacion.ReservaService.Reserva> RegistrarReservaAsync(TAGO_Presentacion.ReservaService.Reserva entidad) {
            return base.Channel.RegistrarReservaAsync(entidad);
        }
        
        public TAGO_Presentacion.ReservaService.Reserva CancelarReserva(TAGO_Presentacion.ReservaService.Reserva entidad) {
            return base.Channel.CancelarReserva(entidad);
        }
        
        public System.Threading.Tasks.Task<TAGO_Presentacion.ReservaService.Reserva> CancelarReservaAsync(TAGO_Presentacion.ReservaService.Reserva entidad) {
            return base.Channel.CancelarReservaAsync(entidad);
        }
    }
}
